# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RavV8goOnTFzpeuGXDxhzzFHXM1tZhZq
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay
from imblearn.over_sampling import RandomOverSampler


# ===============================
# 1. 讀取已前處理完成之資料
# ===============================
data = pd.read_csv("step4_with_continent.csv")


# ===============================
# 2. 定義 X 與 y
# y 為疫苗接種程度（低 / 中 / 高）
# ===============================
X = data[['ratio', 'ratio_dead', 'ratio_full']]

y = pd.qcut(
    data['ratio_full'],
    q=3,
    labels=['Low', 'Medium', 'High']
)


# ===============================
# 3. 資料切分（80% 訓練 / 20% 測試）
# ===============================
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# ===============================
# 4. 類別不平衡處理（僅訓練集）
# ===============================
ros = RandomOverSampler(random_state=42)
X_train_res, y_train_res = ros.fit_resample(X_train, y_train)


# ===============================
# 5. Random Forest 模型訓練
# ===============================
rf_model = RandomForestClassifier(
    n_estimators=201,
    max_depth=20,
    class_weight='balanced',
    random_state=42
)

rf_model.fit(X_train_res, y_train_res)


# ===============================
# 6. 測試集評估（混淆矩陣）
# ===============================
y_pred = rf_model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=y.cat.categories
)
disp.plot(values_format='d')
plt.title("混淆矩陣（測試集）")
plt.show()


# ===============================
# 7. 特徵重要度
# ===============================
importances = rf_model.feature_importances_

plt.bar(X.columns, importances)
plt.title("特徵重要度（Gini importance）")
plt.ylabel("Importance")
plt.show()


# ===============================
# 8. 預測結果分布
# ===============================
pd.Series(y_pred).value_counts().sort_index().plot(
    kind='bar',
    title='測試集預測結果分布'
)
plt.ylabel("筆數")
plt.show()


# ===============================
# 9. 五折分層交叉驗證
# ===============================
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

fold = 1
acc_list = []

for train_idx, val_idx in skf.split(X, y):
    print(f"第 {fold} 折")
    print("訓練資料筆數：", len(train_idx))
    print("驗證資料筆數：", len(val_idx))

    X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

    model = RandomForestClassifier(**rf_model.get_params())
    model.fit(X_tr, y_tr)

    acc = accuracy_score(y_val, model.predict(X_val))
    acc_list.append(acc)

    print("驗證集 Accuracy：", round(acc, 4))
    fold += 1

print("交叉驗證平均 Accuracy：", round(np.mean(acc_list), 4))